# Template paths configuration
# All paths are relative to base_dir

templates:
  # Project structure templates
  project_templates:
    fastapi: templates/fastapi-template
    pyproject: templates/pyproject-template
  
  # Configuration templates
  config_templates:
    lib: config/lib.yaml.template
    service: config/service.yaml.template
    workspace: config/workspace.yaml.template
  
  # Development environment templates
  dev_templates:
    # VSCode and devcontainer templates
    devcontainer:
      json: dev/.devcontainer/devcontainer.json
      dockerfile: dev/.devcontainer/Dockerfile
    
    vscode:
      settings: dev/.vscode/settings.json
      launch: dev/.vscode/launch.json
    
    # Git templates
    git:
      ignore: dev/gitignore.template
      pre_commit: dev/pre-commit-config.yaml
    
    # Docker templates
    docker:
      dockerfile: dev/Dockerfile.template
      ignore: dev/dockerignore.template
      compose: dev/docker-compose.yaml.template
    
    # Project documentation templates
    docs:
      readme: dev/README.md.template
      contributing: dev/CONTRIBUTING.md.template
      changelog: dev/CHANGELOG.md.template
    
    # Build and CI templates
    build:
      makefile: dev/Makefile.template
      pyproject: dev/pyproject.toml.template
    
    ci:
      github_workflows: dev/.github/workflows