# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "tests/*"
  - "docs/*"
  - "**/__init__.py"
