version: '3.8'
services:
  app:
    build: .
    ports:
      {% for port in cookiecutter.service_ports.ports %}
      - '{{ port }}:{{ port }}'
      {% endfor %}
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1